job_desc_transform:
  outputs:
    daily:
      dataset: daily_job_postings
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/app/dbt/gcp.json
      location: us-east1
      method: service-account
      priority: interactive
      project: data-management-2-440220
      threads: 5
      type: bigquery
    historic:
      dataset: historic_job_postings
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/app/dbt/gcp.json
      location: us-east1
      method: service-account
      priority: interactive
      project: data-management-2-440220
      threads: 5
      type: bigquery
  target: daily